openapi: 3.0.0
info:
  description: ShowStarters API for auditing info.
  version: "1.0.0"
  title: ShowStarters Audit API
  contact:
    email: ncrooks@my.bcit.ca
tags:
  - name: customers
    description: Customer related API calls
  - name: booking
    description: Scheduling related API calls
paths:
  /ticket:
    get:
      summary: Gets a ticket purchase from history
      tags:
        - customers
      operationId: app.get_ticket_purchase
      description: Gets ticket purchase from event store
      parameters:
        - name: index
          in: query
          description: Gets the ticket purchase at the index in the event store
          schema:
            type: integer
            example: 5
      responses:
        '200':
          description: Successfully returned ticket purchase
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Ticket'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /show:
    get:
      summary: Gets a show from history
      tags:
        - booking
      operationId: app.get_show
      description: Gets show from event store
      parameters:
        - name: index
          in: query
          description: Gets the show at the index in the event store
          schema:
            type: integer
            example: 5
      responses:
        '200':
          description: Successfully returned show
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Show'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    Ticket:
      type: object
      required:
        - ticket_id
        - ticket_holder
        - show
      properties:
        ticket_id:
          type: integer
          example: 1
        ticket_holder:
          type: string
          example: Barry B. Benson
        show:
          type: integer
          example: 3
        purchase_date:
          type: string
          format: date-time
          example: '2021-08-29T09:12:33.001Z'
        contact:
          type: string
          example: barryhunneyB@thehive.com
        price:
          type: integer
          example: 45

    Show:
      type: object
      required:
        - show_id
        - artist
        - showtime
        - venue
        - available_tickets
      properties:
        show_id:
          type: integer
          example: 1
        artist:
          type: string
          example: Devo
        showtime:
          type: string
          format: date-time
          example: '2021-08-29T17:00:00Z'
        booking_contact:
          type: string
          example: 555-555-5555
        available_tickets:
          type: integer
          example: 500
        venue:
          type: string
          example: The Cranlaravay Cabaret