openapi: 3.0.0
info:
  description: ShowStarters data storage API.
  version: "1.0.0"
  title: ShowStarters Data Storage API
  contact:
    email: ncrooks@my.bcit.ca
tags:
  - name: customers
    description: Customer related API calls
  - name: booking
    description: Scheduling related API calls
paths:
  /ticket:
    get:
      tags:
        - customers
      summary: gets list of purchased tickets
      operationId: app.get_tickets
      description: Gets purchased tickets added after a timestamp
      parameters:
        - name: start_timestamp
          in: query
          description: Filters request by start timestamp
          schema:
            type: string
            format: date-time
            example: '2016-08-29T09:12:33.001Z'
        - name: end_timestamp
          in: query
          description: Filters request by end timestamp
          schema:
            type: string
            format: date-time
            example: '2016-08-29T09:12:33.001Z'
      responses:
        '200':
          description: Successfully returned a list of ticket purchase events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Ticket"
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /show:
    get:
      tags:
        - booking
      summary: gets list of scheduled shows
      operationId: app.get_shows
      description: Gets scheduled shows added after a timestamp
      parameters:
        - name: start_timestamp
          in: query
          description: Filters request by start timestamp
          schema:
            type: string
            format: date-time
            example: '2016-08-29T09:12:33.001Z'
        - name: end_timestamp
          in: query
          description: Filters request by end timestamp
          schema:
            type: string
            format: date-time
            example: '2016-08-29T09:12:33.001Z'
      responses:
        '200':
          description: Successfully returned a list of show schedule events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Show"
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    Ticket:
      type: object
      required:
        - ticket_id
        - ticket_holder
        - show
      properties:
        ticket_id:
          type: integer
          example: 1
        ticket_holder:
          type: string
          example: Barry B. Benson
        show:
          type: integer
          example: 3
        purchase_date:
          type: string
          format: date-time
          example: '2021-08-29T09:12:33.001Z'
        contact:
          type: string
          example: barryhunneyB@thehive.com
        price:
          type: integer
          example: 45

    Show:
      type: object
      required:
        - show_id
        - artist
        - showtime
        - venue
        - available_tickets
      properties:
        show_id:
          type: integer
          example: 1
        artist:
          type: string
          example: Devo
        showtime:
          type: string
          format: date-time
          example: '2021-08-29T17:00:00Z'
        booking_contact:
          type: string
          example: 555-555-5555
        available_tickets:
          type: integer
          example: 500
        venue:
          type: string
          example: The Cranlaravay Cabaret